"""
report_builder.py — Truth-grounded response synthesis

Architecture (Dual-Channel Reporting):

    Channel A — StructuredReport (authoritative)
        Machine-readable. Auditable. Never LLM-generated.
        Built deterministically from MissionPlan + ExecutionResults.

    Channel B — User Narrative (expressive)
        LLM-rendered from StructuredReport.
        Constrained: LLM sees explicit action list + parameters + results.
        Validated: anomalies logged (Phase 2: reject + fallback).

Invariants:
    - The LLM must NEVER invent actions.
    - The LLM must ONLY describe what is in the StructuredReport.
    - Even without an LLM, output is useful and specific.

Two entry points:
  1. build()           — reactive: after a mission completes
  2. build_from_event() — proactive: when a world event deserves a notification
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional

from ir.mission import MissionPlan, MissionNode
from conversation.frame import ConversationFrame
from execution.executor import NodeStatus, ExecutionResult
from world.timeline import WorldTimeline, WorldEvent
from world.snapshot import WorldSnapshot
from models.base import LLMClient


logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────
# Ground Truth Models (Channel A — never LLM-generated)
# ─────────────────────────────────────────────────────────────

class ReportType(str, Enum):
    SUCCESS = "success"
    PARTIAL = "partial"
    FAILURE = "failure"
    INFO = "info"
    PROACTIVE = "proactive"


@dataclass(frozen=True)
class ActionRecord:
    """Single executed action — machine truth, no narrative.

    Built deterministically from MissionNode + ExecutionResult.
    This is never generated by an LLM.

    status uses NodeStatus enum values — see execution/executor.py.
    reason comes from skill metadata (e.g. 'no_media_session').
    """
    node_id: str
    skill: str
    status: str           # NodeStatus value: completed | no_op | failed | skipped | timed_out
    inputs: Dict[str, Any]
    outputs: Dict[str, Any] = field(default_factory=dict)
    error: Optional[str] = None
    reason: Optional[str] = None


@dataclass(frozen=True)
class StructuredReport:
    """Complete structured truth for one mission.

    Channel A — authoritative. Never LLM-generated.
    The LLM receives this as input and can only rephrase it.
    """
    report_type: ReportType
    actions: List[ActionRecord]
    user_query: str
    mission_id: str
    unsupported_requests: List[Dict[str, str]] = field(default_factory=list)


@dataclass(frozen=True)
class EventReportDraft:
    """
    Machine-truth report for a proactive world event.

    event_type: the raw event type string
    summary_fact: single human-readable fact about what happened
    payload_summary: key details extracted from the event payload
    """
    event_type: str
    summary_fact: str
    payload_summary: Dict[str, Any] = field(default_factory=dict)


# ─────────────────────────────────────────────────────────────
# Report Builder
# ─────────────────────────────────────────────────────────────

class ReportBuilder:
    # ─────────────────────────────────────────────────────────
    # Centralized status → user-facing label mapping.
    # To add a new status: add it to NodeStatus enum, then add
    # the label here.  No other file needs status string logic.
    # ─────────────────────────────────────────────────────────
    _STATUS_LABELS: Dict[str, str] = {
        NodeStatus.COMPLETED: "SUCCESS",
        NodeStatus.NO_OP: "NO_OP",
        NodeStatus.SKIPPED: "SKIPPED",
        NodeStatus.FAILED: "FAILED",
        NodeStatus.TIMED_OUT: "TIMED_OUT",
    }

    def __init__(
        self,
        llm: Optional[LLMClient] = None,
        draft_templates: Optional[Dict[str, str]] = None,
    ):
        self.llm = llm
        self._draft_templates: Dict[str, str] = draft_templates or {}

    # ─────────────────────────────────────────────────────────
    # REACTIVE: Post-mission reporting
    # ─────────────────────────────────────────────────────────

    def build(
        self,
        mission: MissionPlan,
        execution_result: ExecutionResult,
        timeline: WorldTimeline,
        snapshot: WorldSnapshot,
        conversation: ConversationFrame,
        queued_insights: Optional[List[str]] = None,
        pre_narration: Optional[str] = None,
    ) -> str:
        """
        Returns final user-facing text after mission execution.

        Accepts FULL ExecutionResult (not just .results) so that
        node_statuses and metadata flow losslessly into Channel A.

        Args:
            queued_insights: Proactive notifications queued during execution.
                             Merged into the LLM prompt for contextual integration.
            pre_narration: Text already spoken before execution started.
                           Passed to LLM to prevent tonal repetition.

        Flow:
        1. Build StructuredReport (Channel A — authoritative)
        2. Render via LLM (Channel B — constrained narrative)
        3. Validate response against structured truth
        4. Fall back to deterministic text if anything fails
        """

        report = self._build_structured_report(
            mission, execution_result, conversation,
        )

        # If no LLM configured → deterministic fallback
        if not self.llm:
            return self._fallback_text(report)

        try:
            response = self._render_with_llm(
                report, conversation,
                queued_insights=queued_insights,
                pre_narration=pre_narration,
            )
            self._validate_response(response, report)
            return response
        except Exception:
            # Absolute safety net
            return self._fallback_text(report)

    # ─────────────────────────────────────────────────────────
    # PROACTIVE: Event-driven reporting (unchanged)
    # ─────────────────────────────────────────────────────────

    def build_from_event(
        self,
        event: WorldEvent,
        snapshot: WorldSnapshot,
        conversation: ConversationFrame,
    ) -> Optional[str]:
        """
        Returns user-facing text for a proactive event notification,
        or None if the event should result in silence.

        Decision to speak is deterministic.
        LLM only formats the message.
        """

        draft = self._build_event_draft(event)

        if draft is None:
            return None

        # Background severity events skip LLM — deterministic text only
        severity = event.payload.get("severity", "info")
        if not self.llm or severity == "background":
            return self._fallback_event_text(draft)

        try:
            return self._render_event_with_llm(draft, snapshot, conversation)
        except Exception:
            return self._fallback_event_text(draft)

    # ─────────────────────────────────────────────────────────
    # REFLEX RICH: Skill result reporting (Phase 14)
    # ─────────────────────────────────────────────────────────

    def build_from_skill_result(
        self,
        skill_name: str,
        inputs: Dict[str, Any],
        outputs: Dict[str, Any],
        user_query: str,
        snapshot: WorldSnapshot,
        conversation: "ConversationFrame",
    ) -> str:
        """Returns user-facing text for a single skill's output.

        Third input type: alongside build() for missions and
        build_from_event() for proactive events.

        Used when a reflex-routed skill has output_style="rich" —
        its structured data (lists, dicts) needs LLM narration
        instead of raw f"{k}: {v}" dumps.

        No MissionPlan is fabricated. The StructuredReport is built
        directly from the skill result.

        Scaling note: _describe_action() summarizes lists as "{N} items"
        so the LLM prompt stays bounded. However, the LLM can't enumerate
        items it didn't see. When list skills (list_files, list_tabs) arrive
        with potentially 50+ items, introduce a list_size_threshold:
            ≤ threshold → pass items inline (LLM enumerates)
            > threshold → pass count + sample (LLM summarizes)
        """
        if not self.llm:
            return self._format_skill_fallback(skill_name, outputs, user_query)

        try:
            return self._render_skill_result_with_llm(
                skill_name, inputs, outputs, user_query,
                snapshot, conversation,
            )
        except Exception:
            return self._format_skill_fallback(skill_name, outputs, user_query)

    def _render_skill_result_with_llm(
        self,
        skill_name: str,
        inputs: Dict[str, Any],
        outputs: Dict[str, Any],
        user_query: str,
        snapshot: "WorldSnapshot",
        conversation: "ConversationFrame",
    ) -> str:
        """Render a skill result using a result-focused LLM prompt.

        Unlike _render_with_llm() (mission prompt), this prompt:
        - Talks about the outcome, not the execution process
        - Never mentions plans, nodes, or system internals
        - Includes the user's original query for context
        """
        prompt = self._build_skill_result_prompt(
            skill_name, outputs, user_query, conversation,
        )
        response = self.llm.complete(prompt)
        return response.strip()

    def _build_skill_result_prompt(
        self,
        skill_name: str,
        outputs: Dict[str, Any],
        user_query: str,
        conversation: "ConversationFrame",
    ) -> str:
        """Build a result-focused prompt for reflex skill output.

        This is NOT the mission prompt. It focuses on what the user
        asked and what the result is — no execution terminology.
        """
        # Format outputs for prompt
        result_lines = []
        for key, val in outputs.items():
            if isinstance(val, list):
                if len(val) == 0:
                    result_lines.append(f"  {key}: (empty list)")
                elif len(val) <= 10:
                    result_lines.append(f"  {key}: {val}")
                else:
                    result_lines.append(
                        f"  {key}: {len(val)} items "
                        f"(first 5: {val[:5]})"
                    )
            elif isinstance(val, dict):
                result_lines.append(f"  {key}: {val}")
            else:
                result_lines.append(f"  {key}: {val}")

        result_block = "\n".join(result_lines) if result_lines else "  (no data)"

        return f"""You are MERLIN, a calm, precise, intelligent assistant.

The user asked: "{user_query}"

The result is:
{result_block}

Conversation context:
- Active domain: {conversation.active_domain}
- Active entity: {conversation.active_entity}

Instructions:
- Answer the user's question naturally based on the result above.
- Be concise — one to three sentences.
- Speak naturally, like JARVIS.
- Do NOT mention plans, nodes, execution reports, or internal processes.
- Do NOT say "I executed" or "I ran" or "the skill returned".
- Only talk about the outcome — what the user asked about.
- If the result is empty, say so clearly and helpfully.
- If the result contains items, enumerate them naturally.

Respond with plain text only."""

    @staticmethod
    def _format_skill_fallback(
        skill_name: str,
        outputs: Dict[str, Any],
        user_query: str,
    ) -> str:
        """Deterministic fallback for skill results when LLM is unavailable."""
        if not outputs:
            return f"Done. ({skill_name})"

        parts = []
        for key, val in outputs.items():
            if isinstance(val, list):
                if len(val) == 0:
                    parts.append(f"No {key} found.")
                else:
                    parts.append(f"{len(val)} {key}.")
            elif val is not None:
                parts.append(f"{key}: {val}")

        return " ".join(parts) if parts else f"Done. ({skill_name})"

    # ─────────────────────────────────────────────────────────
    # Channel A: Structured Report Construction
    # ─────────────────────────────────────────────────────────

    def _build_structured_report(
        self,
        mission: MissionPlan,
        exec_result: ExecutionResult,
        conversation: ConversationFrame,
    ) -> StructuredReport:
        """Build a StructuredReport from mission plan + typed ExecutionResult.

        Reads node_statuses for semantic classification (completed vs no_op).
        Reads metadata for reason (e.g. 'no_media_session').
        This is the single source of truth — no natural language yet.
        """
        actions: List[ActionRecord] = []

        for node in mission.nodes:
            node_status = exec_result.node_statuses.get(node.id)
            meta = exec_result.metadata.get(node.id, {})

            if node_status in (NodeStatus.COMPLETED, NodeStatus.NO_OP):
                actions.append(ActionRecord(
                    node_id=node.id,
                    skill=node.skill,
                    status=node_status.value,
                    inputs=self._sanitize_inputs(node.inputs),
                    outputs=exec_result.results.get(node.id, {}),
                    reason=meta.get("reason"),
                ))
            elif node_status == NodeStatus.SKIPPED:
                actions.append(ActionRecord(
                    node_id=node.id,
                    skill=node.skill,
                    status=NodeStatus.SKIPPED.value,
                    inputs=self._sanitize_inputs(node.inputs),
                ))
            elif node_status in (NodeStatus.FAILED, NodeStatus.TIMED_OUT):
                actions.append(ActionRecord(
                    node_id=node.id,
                    skill=node.skill,
                    status=node_status.value,
                    inputs=self._sanitize_inputs(node.inputs),
                    error=f"Node {node_status.value}",
                ))
            else:
                # Node never executed (missing from results entirely)
                actions.append(ActionRecord(
                    node_id=node.id,
                    skill=node.skill,
                    status=NodeStatus.FAILED.value,
                    inputs=self._sanitize_inputs(node.inputs),
                    error="Execution did not produce output for this node",
                ))

        # Classify report type using NodeStatus semantics.
        # NO_OP counts as 'completed' for overall success determination
        # because the skill executed without error.
        completed = [a for a in actions if a.status in (
            NodeStatus.COMPLETED.value, NodeStatus.NO_OP.value,
        )]
        failures = [a for a in actions if a.status in (
            NodeStatus.FAILED.value, NodeStatus.TIMED_OUT.value,
        )]

        report_type = (
            ReportType.SUCCESS if completed and not failures else
            ReportType.PARTIAL if completed and failures else
            ReportType.FAILURE
        )

        # Extract user query from conversation history (last user turn)
        user_query = ""
        for turn in reversed(conversation.history):
            if turn.role == "user":
                user_query = turn.text
                break

        return StructuredReport(
            report_type=report_type,
            actions=actions,
            user_query=user_query,
            mission_id=mission.id,
            unsupported_requests=mission.metadata.get(
                "unsupported_intents", [],
            ),
        )

    @staticmethod
    def _sanitize_inputs(inputs: Dict[str, Any]) -> Dict[str, Any]:
        """Sanitize node inputs for inclusion in StructuredReport.

        Converts OutputReference objects to their string representation.
        Keeps primitives as-is.
        """
        sanitized = {}
        for key, val in inputs.items():
            if hasattr(val, "node") and hasattr(val, "output"):
                # OutputReference — resolve to readable string
                sanitized[key] = f"<ref:{val.node}.{val.output}>"
            else:
                sanitized[key] = val
        return sanitized

    # ─────────────────────────────────────────────────────────
    # Channel B: Constrained LLM Rendering
    # ─────────────────────────────────────────────────────────

    def _render_with_llm(
        self,
        report: StructuredReport,
        conversation: ConversationFrame,
        queued_insights: Optional[List[str]] = None,
        pre_narration: Optional[str] = None,
    ) -> str:
        prompt = self._build_llm_prompt(
            report, conversation,
            queued_insights=queued_insights,
            pre_narration=pre_narration,
        )
        response = self.llm.complete(prompt)
        return response.strip()

    def _build_llm_prompt(
        self,
        report: StructuredReport,
        conversation: ConversationFrame,
        queued_insights: Optional[List[str]] = None,
        pre_narration: Optional[str] = None,
    ) -> str:
        """Build a constrained LLM prompt from StructuredReport.

        The LLM sees:
        - Every action with its status, inputs, and outputs
        - Explicit failure details
        - Strict instructions to not invent actions
        - What was already announced (tonal continuity)
        - Queued proactive insights for contextual merging

        This is the grounding mechanism. The LLM cannot hallucinate
        because every fact it needs is explicitly provided.
        """
        # Build explicit action list using centralized status labels
        action_lines = []
        for i, action in enumerate(report.actions, 1):
            tag = self._STATUS_LABELS.get(action.status, action.status.upper())
            desc = self._describe_action(action)
            action_lines.append(f"  {i}. [{tag}] {desc}")

        actions_block = "\n".join(action_lines) if action_lines else "  (none)"

        # Build issues detail (failures + no-ops with reasons)
        issues = [a for a in report.actions
                  if a.status not in (NodeStatus.COMPLETED.value,)]
        if issues:
            issue_lines = []
            for a in issues:
                if a.status == NodeStatus.NO_OP.value:
                    issue_lines.append(
                        f"  - {a.skill} ({a.node_id}): NO_OP "
                        f"— {a.reason or 'no change needed'}"
                    )
                elif a.error:
                    issue_lines.append(
                        f"  - {a.skill} ({a.node_id}): {a.error}"
                    )
                else:
                    issue_lines.append(
                        f"  - {a.skill} ({a.node_id}): {a.status}"
                    )
            issues_block = "\n".join(issue_lines)
        else:
            issues_block = "  none"

        # ── Tonal continuity: what the user already heard ──
        pre_narration_block = ""
        if pre_narration:
            pre_narration_block = (
                f"\nAlready announced to user: \"{pre_narration}\"\n"
                f"Do NOT repeat or rephrase this. "
                f"Continue naturally from where it left off.\n"
            )

        # ── Queued proactive insights for contextual merging ──
        insights_block = ""
        if queued_insights:
            insight_lines = "\n".join(
                f"  - {insight}" for insight in queued_insights
            )
            insights_block = (
                f"\nAdditional context (integrate naturally if relevant, "
                f"otherwise omit):\n{insight_lines}\n"
            )

        # Build unsupported requests block
        if report.unsupported_requests:
            unsupported_lines = []
            for u in report.unsupported_requests:
                desc = u.get("description", "unknown")
                unsupported_lines.append(f"  - {desc}")
            unsupported_block = "\n".join(unsupported_lines)
        else:
            unsupported_block = "  none"

        # ── Generated content: extract long outputs for dedicated block ──
        content_blocks = []
        for action in report.actions:
            if action.status != NodeStatus.COMPLETED.value:
                continue
            for key, val in action.outputs.items():
                if isinstance(val, str) and len(val) > 200:
                    content_blocks.append(
                        f"  [{action.skill} → {key}]:\n"
                        f"  {val}"
                    )

        generated_block = ""
        if content_blocks:
            generated_block = (
                "\nGenerated content (present this to the user):\n"
                + "\n\n".join(content_blocks)
                + "\n"
            )

        return f"""You are MERLIN, a calm, precise, intelligent assistant.

Convert the following execution report into a concise user-facing message.
Do NOT add actions. Do NOT infer additional tasks.
Only describe what is explicitly listed below.

Context: The assistant executed the following plan.
Result: {report.report_type.value}

Executed actions:
{actions_block}

Unsupported requests (NOT executed — do NOT claim these happened):
{unsupported_block}

Issues:
{issues_block}
{pre_narration_block}{insights_block}{generated_block}
Conversation context:
- Active domain: {conversation.active_domain}
- Active entity: {conversation.active_entity}

Instructions:
- Speak naturally, like JARVIS.
- Be concise — one to three sentences for operational actions.
- Reference specific names and results from the executed actions above.
- For unsupported requests, state clearly that they were not performed.
- [NO_OP] means the action was attempted but had no effect. Report it honestly.
  Do NOT claim a NO_OP action succeeded. State the reason if provided.
- If there are failures, explain calmly and suggest what the user can do.
- Do NOT claim actions that are not listed under executed actions.
- Do NOT promise future actions.
- Do NOT add commentary about the system.
- If generated content is present, include it in your response.
  Introduce it briefly, then present the content itself.

Respond with plain text only."""

    @staticmethod
    def _describe_action(action: ActionRecord) -> str:
        """Build a human-readable description of a single action.

        Used in both LLM prompts and deterministic fallback.
        Uses NodeStatus values — never hardcoded strings.
        """
        skill_short = action.skill.rsplit(".", 1)[-1] if "." in action.skill else action.skill
        parts = [f"{skill_short}:"]

        # Add input details — ALL contract-bound inputs, no whitelist.
        # Safety filters: skip internal keys, reference tokens, large objects.
        for key, val in action.inputs.items():
            if key.startswith("_"):
                continue  # internal-only fields
            if isinstance(val, bool):
                parts.append(f'{key}="{("yes" if val else "no")}"')
            elif isinstance(val, (int, float)):
                parts.append(f'{key}="{val}"')
            elif isinstance(val, str):
                if val.startswith("<ref:"):
                    continue  # output reference token
                parts.append(f'{key}="{val}"')
            elif isinstance(val, list) and len(val) <= 5:
                parts.append(f'{key}={val}')

        # Add reason for no-op actions (takes priority over raw outputs)
        if action.reason:
            parts.append(f'(reason: {action.reason})')
        # Add ALL output details for completed actions.
        # Outputs are contract-bound — only declared keys appear.
        # Large structures (list/dict) are summarized to prevent
        # prompt blowup. Long strings are truncated with preview.
        elif action.status == NodeStatus.COMPLETED.value and action.outputs:
            for key, val in action.outputs.items():
                if isinstance(val, bool):
                    parts.append(f'→ {key}="{("yes" if val else "no")}"')
                elif isinstance(val, str):
                    if len(val) > 200:
                        # Long content (generated text, file content) —
                        # truncate to preview. Full content is in the
                        # dedicated content block.
                        preview = val[:100].replace("\n", " ")
                        parts.append(
                            f'→ {key}="{preview}..." '
                            f'({len(val)} chars)'
                        )
                    else:
                        parts.append(f'→ {key}="{val}"')
                elif isinstance(val, (int, float)):
                    parts.append(f'→ {key}="{val}"')
                elif isinstance(val, list):
                    parts.append(f'→ {key}="{len(val)} items"')
                elif isinstance(val, dict):
                    parts.append(f'→ {key}="{len(val)} entries"')

        # Add error for failed/timed-out actions
        if action.status in (NodeStatus.FAILED.value, NodeStatus.TIMED_OUT.value) and action.error:
            parts.append(f'[error: {action.error}]')

        return " ".join(parts)

    # ─────────────────────────────────────────────────────────
    # Soft Validation (Phase 1: log anomalies, no rejection)
    # ─────────────────────────────────────────────────────────

    def _validate_response(
        self, response: str, report: StructuredReport,
    ) -> None:
        """Validate LLM response against structured truth.

        Phase 2: Reject hallucinated content, fall back to deterministic text.

        Checks:
        - LLM should mention entities from the report
        - LLM should not mention file names/extensions not present in
          executed actions or unsupported descriptions
        """
        # Extract known entity names from structured report
        known_entities: set[str] = set()
        for action in report.actions:
            for val in action.inputs.values():
                if isinstance(val, str) and not val.startswith("<ref:"):
                    known_entities.add(val.lower())
            for val in action.outputs.values():
                if isinstance(val, str):
                    # Extract just the filename/foldername from paths
                    clean = val.replace("\\", "/").rstrip("/")
                    if "/" in clean:
                        known_entities.add(clean.rsplit("/", 1)[-1].lower())
                    known_entities.add(val.lower())

        # Also include unsupported request descriptions as known context
        for u in report.unsupported_requests:
            desc = u.get("description", "")
            if desc:
                known_entities.add(desc.lower())

        if not known_entities:
            return

        response_lower = response.lower()

        # Check: did the LLM mention at least one known entity?
        mentioned_any = any(
            entity in response_lower for entity in known_entities
            if len(entity) > 1  # Skip single-char to avoid false positives
        )

        if not mentioned_any and report.actions:
            logger.warning(
                "[VALIDATION] LLM response does not mention any known entities. "
                "Known: %s. Response: '%s'",
                sorted(known_entities)[:10],
                response[:200],
            )

        # Defense-in-depth: detect hallucinated file names
        # Extract filenames (word.ext patterns) from LLM response
        file_pattern = re.compile(r'\b[\w.-]+\.(?:py|txt|md|js|ts|html|css|json|yaml|yml|csv|xml|sh|bat|exe|log)\b', re.IGNORECASE)
        mentioned_files = set(m.lower() for m in file_pattern.findall(response))

        if mentioned_files:
            # Build set of known filenames from actions + unsupported
            known_files: set[str] = set()
            for action in report.actions:
                for val in action.inputs.values():
                    if isinstance(val, str):
                        known_files.update(
                            m.lower() for m in file_pattern.findall(val)
                        )
                for val in action.outputs.values():
                    if isinstance(val, str):
                        known_files.update(
                            m.lower() for m in file_pattern.findall(val)
                        )
            for u in report.unsupported_requests:
                desc = u.get("description", "")
                known_files.update(
                    m.lower() for m in file_pattern.findall(desc)
                )

            hallucinated_files = mentioned_files - known_files
            if hallucinated_files:
                logger.warning(
                    "[VALIDATION] LLM response mentions files not in report: %s. "
                    "Rejecting — falling back to deterministic text.",
                    sorted(hallucinated_files),
                )
                raise ValueError(
                    f"Hallucinated files detected: {hallucinated_files}"
                )

    # ─────────────────────────────────────────────────────────
    # Deterministic draft builders (proactive — unchanged)
    # ─────────────────────────────────────────────────────────

    def _build_event_draft(
        self,
        event: WorldEvent,
    ) -> Optional[EventReportDraft]:
        """
        Build a deterministic event draft.

        Uses config-driven templates from _draft_templates.
        Templates are purely formatting — no logic in YAML.
        Falls back to event type name if no template matches.
        Returns None only for completely unknown events with no template.
        """

        et = event.type
        p = event.payload

        # ── Config-driven templates (primary path) ──
        template = self._draft_templates.get(et)
        if template is not None:
            summary = self._safe_format(template, p)
            return EventReportDraft(
                event_type=et,
                summary_fact=summary,
                payload_summary=p,
            )

        # ── No template: silence ──
        return None

    @staticmethod
    def _safe_format(template: str, payload: Dict[str, Any]) -> str:
        """
        Format a template string with payload values.
        Missing keys produce the literal {key} placeholder — never crashes.
        """
        try:
            # Use format_map with defaultdict for safe interpolation
            from collections import defaultdict
            safe_payload = defaultdict(lambda: "?", payload)
            return template.format_map(safe_payload)
        except Exception:
            return f"Event: {template}"

    # ─────────────────────────────────────────────────────────
    # LLM rendering — proactive event reports (unchanged)
    # ─────────────────────────────────────────────────────────

    def _render_event_with_llm(
        self,
        draft: EventReportDraft,
        snapshot: WorldSnapshot,
        conversation: ConversationFrame,
    ) -> str:
        prompt = self._build_event_llm_prompt(draft, snapshot, conversation)

        response = self.llm.complete(prompt)
        return response.strip()

    def _build_event_llm_prompt(
        self,
        draft: EventReportDraft,
        snapshot: WorldSnapshot,
        conversation: ConversationFrame,
    ) -> str:
        # Filtered world context — only relevant sections, never full dump
        world_context = self._build_world_context(snapshot)

        return f"""
You are MERLIN, a calm, precise, intelligent assistant.
You are proactively notifying the user about something that just happened.
You were NOT asked about this — you are volunteering the information.

Fact:
- {draft.summary_fact}

{world_context}Conversation context:
- Active domain: {conversation.active_domain}
- Active entity: {conversation.active_entity}

Instructions:
- Speak naturally, like JARVIS.
- Be brief — one or two sentences maximum.
- Weave world context naturally into your phrasing when relevant.
- Do NOT explain how you know this.
- Do NOT ask follow-up questions unless critical.
- Do NOT invent details not in the facts.
- Sound confident and calm.

Respond with plain text only.
"""

    @staticmethod
    def _build_world_context(snapshot: WorldSnapshot) -> str:
        """
        Build filtered world context for LLM prompt.
        Only includes relevant sections — never full state dump.
        """
        parts = []

        # Foreground app
        if snapshot.state.active_app:
            parts.append(f"- Foreground app: {snapshot.state.active_app}")

        # Media
        if snapshot.state.media and snapshot.state.media.is_playing:
            media = snapshot.state.media
            track = media.title or "unknown"
            if media.artist:
                track = f"{media.artist} — {track}"
            platform = media.platform or "media player"
            parts.append(f"- Media: {platform} playing \"{track}\"")

        # System resources (only non-normal values)
        hw = snapshot.state.system.hardware
        res = snapshot.state.system.resources
        if hw.battery_percent is not None:
            charging = " (charging)" if hw.battery_charging else " (discharging)"
            parts.append(f"- Battery: {hw.battery_percent}%{charging}")
        if res.cpu_status == "high" and res.cpu_percent is not None:
            parts.append(f"- CPU: {res.cpu_percent}% (elevated)")
        if res.memory_status == "high" and res.memory_percent is not None:
            parts.append(f"- RAM: {res.memory_percent}% (pressure)")

        if not parts:
            return ""

        return "World context:\n" + "\n".join(parts) + "\n"

    # ─────────────────────────────────────────────────────────
    # Deterministic fallbacks
    # ─────────────────────────────────────────────────────────

    def _fallback_text(self, report: StructuredReport) -> str:
        """Deterministic fallback — specific and useful even without LLM.

        Produces per-action descriptions instead of generic counts.
        Uses NodeStatus values via centralized labels.
        Includes unsupported requests for completeness.
        """
        lines = []

        for action in report.actions:
            desc = self._describe_action(action)
            if action.status == NodeStatus.COMPLETED.value:
                lines.append(f"Done: {desc}")
            elif action.status == NodeStatus.NO_OP.value:
                reason = action.reason or "no change needed"
                lines.append(f"No action: {desc} ({reason})")
            elif action.status in (NodeStatus.FAILED.value, NodeStatus.TIMED_OUT.value):
                lines.append(f"Failed: {desc}")
            elif action.status == NodeStatus.SKIPPED.value:
                lines.append(f"Skipped: {desc}")

        for u in report.unsupported_requests:
            lines.append(f"Not supported: {u.get('description', '?')}")

        return " ".join(lines) if lines else "Done."

    def _fallback_event_text(self, draft: EventReportDraft) -> str:
        return draft.summary_fact

